### ISSUE TITLE
出现未知变量

### ISSUE THREAD

**Issue by zhangzonghong** [DataXujing/YOLO-v5#15]
Traceback (most recent call last):
  File "G:/YOLO-v5-master/train.py", line 399, in <module>
    train(hyp)
  File "G:/YOLO-v5-master/train.py", line 201, in train
    tb_writer.add_histogram('classes', c, 0)
NameError: name 'tb_writer' is not defined
这是报错的原因，'tb_writer'哪来的呢，没有定义

**Comment by DataXujing** [comment]
tensorboard.....
