### ISSUE TITLE
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by liuhuaijjin** [DataXujing/YOLO-v5#23]
Traceback (most recent call last):
  File "/home/hqu/yolov5/models/yolo.py", line 274, in <module>
    model = Model(opt.cfg).to(device)
  File "/home/hqu/yolov5/models/yolo.py", line 95, in __init__
    self._initialize_biases()  # only run once
  File "/home/hqu/yolov5/models/yolo.py", line 150, in _initialize_biases
    b[:,4] = b[:,4]+math.log(8 / (640 / s) ** 2)  # obj (8 objects per 640 image)
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.
博主，我在train过程中报这个错误，不知道怎么解决了，我的环境是RTX3090+CUDA11+pytorch1.8。跑ultralytics的yolo.py也报这个错误。

**Comment by DataXujing** [comment]
Pytorch版本太高导致的吧，可以试着降低Pytorch版本

**Comment by liuhuaijjin** [comment]
非常感谢您的回复，问题已经解决，是版本太高的原因，降到pytorch1.7就可以了



---Original---

**Comment by HorizonLiang** [comment]
改成这样就好了：
with torch.no_grad():
    b[:, 4] += math.log(8 / (640 / s) ** 2)  # obj (8 objects per 640 image)
    b[:, 5:] += math.log(0.6 / (m.nc - 0.99)) if cf is None else torch.log(cf / cf.sum())  # cls
